/*
 Navicat Premium Data Transfer

 Source Server         : libolin4
 Source Server Type    : MySQL
 Source Server Version : 80039 (8.0.39)
 Source Host           : 127.0.0.1:3306
 Source Schema         : my_db

 Target Server Type    : MySQL
 Target Server Version : 80039 (8.0.39)
 File Encoding         : 65001

 Date: 08/07/2025 15:01:55
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for solution
-- ----------------------------
DROP TABLE IF EXISTS `solution`;
CREATE TABLE `solution`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `problem_id` int NULL DEFAULT NULL,
  `language_id` int NULL DEFAULT NULL,
  `code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `problem_id`(`problem_id` ASC) USING BTREE,
  INDEX `language_id`(`language_id` ASC) USING BTREE,
  CONSTRAINT `solution_ibfk_1` FOREIGN KEY (`problem_id`) REFERENCES `problem` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `solution_ibfk_2` FOREIGN KEY (`language_id`) REFERENCES `language` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 154 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of solution
-- ----------------------------
INSERT INTO `solution` VALUES (1, 1, 1, 'def two_sum(nums, target):\n    for i in range(len(nums)):\n        for j in range(i+1, len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]');
INSERT INTO `solution` VALUES (2, 1, 2, 'public int[] twoSum(int[] nums, int target) {\n    for (int i = 0; i < nums.length; i++) {\n        for (int j = i + 1; j < nums.length; j++) {\n            if (nums[i] + nums[j] == target) {\n                return new int[]{i, j};\n            }\n        }\n    }\n    return null;\n}');
INSERT INTO `solution` VALUES (3, 1, 3, '#include <stdio.h>\nint* twoSum(int* nums, int numsSize, int target, int* returnSize) {\n    for (int i = 0; i < numsSize; i++) {\n        for (int j = i + 1; j < numsSize; j++) {\n            if (nums[i] + nums[j] == target) {\n                int* result = malloc(2 * sizeof(int));\n                result[0] = i; result[1] = j;\n                *returnSize = 2;\n                return result;\n            }\n        }\n    }\n    return NULL;\n}');
INSERT INTO `solution` VALUES (4, 2, 1, 'def lengthOfLongestSubstring(s):\n    start = maxLength = 0\n    usedChar = {}\n    for i in range(len(s)):\n        if s[i] in usedChar and start <= usedChar[s[i]]:\n            start = usedChar[s[i]] + 1\n        else:\n            maxLength = max(maxLength, i - start + 1)\n        usedChar[s[i]] = i\n    return maxLength');
INSERT INTO `solution` VALUES (5, 2, 2, 'public int lengthOfLongestSubstring(String s) {\n    int maxLength = 0;\n    Map<Character, Integer> map = new HashMap<>();\n    for (int i = 0, j = 0; j < s.length(); j++) {\n        if (map.containsKey(s.charAt(j))) {\n            i = Math.max(map.get(s.charAt(j)) + 1, i);\n        }\n        map.put(s.charAt(j), j);\n        maxLength = Math.max(maxLength, j - i + 1);\n    }\n    return maxLength;\n}');
INSERT INTO `solution` VALUES (6, 2, 3, '#include <string.h>\nint lengthOfLongestSubstring(char * s) {\n    int lastIndex[128] = {0}, maxLen = 0, start = 0;\n    for (int i = 0; s[i]; i++) {\n        start = lastIndex[s[i]] > start ? lastIndex[s[i]] : start;\n        int len = i - start + 1;\n        maxLen = maxLen > len ? maxLen : len;\n        lastIndex[s[i]] = i + 1;\n    }\n    return maxLen;\n}');
INSERT INTO `solution` VALUES (7, 3, 1, 'def longestPalindrome(s):\n    if not s: return \"\"\n    start = end = 0\n    for i in range(len(s)):\n        # 以单个字符为中心扩展\n        len1 = expandAroundCenter(s, i, i)\n        # 以两个字符为中心扩展\n        len2 = expandAroundCenter(s, i, i+1)\n        max_len = max(len1, len2)\n        if max_len > end - start:\n            start = i - (max_len - 1) // 2\n            end = i + max_len // 2\n    return s[start:end+1]\n\ndef expandAroundCenter(s, left, right):\n    L, R = left, right\n    while L >=0 and R < len(s) and s[L] == s[R]:\n        L -= 1\n        R += 1\n    return R - L - 1');
INSERT INTO `solution` VALUES (8, 3, 2, 'public class Solution {\n    public String longestPalindrome(String s) {\n        if (s == null || s.length() < 1) return \"\";\n        int start = 0, end = 0;\n        for (int i = 0; i < s.length(); i++) {\n            int len1 = expandAroundCenter(s, i, i);\n            int len2 = expandAroundCenter(s, i, i + 1);\n            int len = Math.max(len1, len2);\n            if (len > end - start) {\n                start = i - (len - 1) / 2;\n                end = i + len / 2;\n            }\n        }\n        return s.substring(start, end + 1);\n    }\n    private int expandAroundCenter(String s, int left, int right) {\n        int L = left, R = right;\n        while (L >= 0 && R < s.length() && s.charAt(L) == s.charAt(R)) {\n            L--;\n            R++;\n        }\n        return R - L - 1;\n    }\n}');
INSERT INTO `solution` VALUES (9, 3, 3, '#include <stdio.h>\n#include <string.h>\nchar * longestPalindrome(char * s) {\n    if (s[0] == \'\\0\') return \"\";\n    int start = 0, end = 0;\n    int len = strlen(s);\n    for (int i = 0; i < len; i++) {\n        int len1 = expandAroundCenter(s, i, i);\n        int len2 = expandAroundCenter(s, i, i + 1);\n        int max_len = (len1 > len2) ? len1 : len2;\n        if (max_len > end - start) {\n            start = i - (max_len - 1) / 2;\n            end = i + max_len / 2;\n        }\n    }\n    int sub_len = end - start + 1;\n    char *result = (char *)malloc((sub_len + 1) * sizeof(char));\n    strncpy(result, s + start, sub_len);\n    result[sub_len] = \'\\0\';\n    return result;\n}\nint expandAroundCenter(char *s, int left, int right) {\n    int L = left, R = right;\n    while (L >= 0 && R < strlen(s) && s[L] == s[R]) {\n        L--;\n        R++;\n    }\n    return R - L - 1;\n}');
INSERT INTO `solution` VALUES (10, 4, 1, 'def maxArea(height):\n    left, right = 0, len(height) - 1\n    max_area = 0\n    while left < right:\n        current_area = min(height[left], height[right]) * (right - left)\n        max_area = max(max_area, current_area)\n        if height[left] < height[right]:\n            left += 1\n        else:\n            right -= 1\n    return max_area');
INSERT INTO `solution` VALUES (11, 4, 2, 'public class Solution {\n    public int maxArea(int[] height) {\n        int left = 0, right = height.length - 1;\n        int maxArea = 0;\n        while (left < right) {\n            maxArea = Math.max(maxArea, Math.min(height[left], height[right]) * (right - left));\n            if (height[left] < height[right])\n                left++;\n            else\n                right--;\n        }\n        return maxArea;\n    }\n}');
INSERT INTO `solution` VALUES (12, 4, 3, '#include <stdio.h>\nint maxArea(int* height, int heightSize) {\n    int left = 0, right = heightSize - 1;\n    int max_area = 0;\n    while (left < right) {\n        int current_area = (height[left] < height[right] ? height[left] : height[right]) * (right - left);\n        if (current_area > max_area) {\n            max_area = current_area;\n        }\n        if (height[left] < height[right]) {\n            left++;\n        } else {\n            right--;\n        }\n    }\n    return max_area;\n}');
INSERT INTO `solution` VALUES (13, 5, 1, 'def threeSum(nums):\n    nums.sort()\n    result = []\n    for i in range(len(nums)-2):\n        # 跳过重复的元素\n        if i > 0 and nums[i] == nums[i-1]:\n            continue\n        left, right = i+1, len(nums)-1\n        while left < right:\n            total = nums[i] + nums[left] + nums[right]\n            if total < 0:\n                left += 1\n            elif total > 0:\n                right -= 1\n            else:\n                result.append([nums[i], nums[left], nums[right]])\n                # 跳过重复的元素\n                while left < right and nums[left] == nums[left+1]:\n                    left += 1\n                while left < right and nums[right] == nums[right-1]:\n                    right -= 1\n                left += 1\n                right -= 1\n    return result');
INSERT INTO `solution` VALUES (14, 5, 2, 'import java.util.ArrayList;\nimport java.util.Arrays;\nimport java.util.List;\n\npublic class Solution {\n    public List<List<Integer>> threeSum(int[] nums) {\n        Arrays.sort(nums);\n        List<List<Integer>> result = new ArrayList<>();\n        for (int i = 0; i < nums.length - 2; i++) {\n            if (i > 0 && nums[i] == nums[i - 1]) continue;\n            int left = i + 1, right = nums.length - 1;\n            while (left < right) {\n                int sum = nums[i] + nums[left] + nums[right];\n                if (sum < 0) {\n                    left++;\n                } else if (sum > 0) {\n                    right--;\n                } else {\n                    result.add(Arrays.asList(nums[i], nums[left], nums[right]));\n                    while (left < right && nums[left] == nums[left + 1]) left++;\n                    while (left < right && nums[right] == nums[right - 1]) right--;\n                    left++;\n                    right--;\n                }\n            }\n        }\n        return result;\n    }\n}');
INSERT INTO `solution` VALUES (15, 5, 3, '#include <stdio.h>\n#include <stdlib.h>\n\nint compare(const void *a, const void *b) {\n    return (*(int*)a - *(int*)b);\n}\n\nint** threeSum(int* nums, int numsSize, int* returnSize, int** returnColumnSizes) {\n    if (numsSize < 3) {\n        *returnSize = 0;\n        return NULL;\n    }\n    qsort(nums, numsSize, sizeof(int), compare);\n    int max_size = numsSize * numsSize;\n    int** result = (int**)malloc(max_size * sizeof(int*));\n    *returnColumnSizes = (int*)malloc(max_size * sizeof(int));\n    *returnSize = 0;\n    for (int i = 0; i < numsSize - 2; i++) {\n        if (i > 0 && nums[i] == nums[i-1]) continue;\n        int left = i + 1;\n        int right = numsSize - 1;\n        while (left < right) {\n            int sum = nums[i] + nums[left] + nums[right];\n            if (sum < 0) {\n                left++;\n            } else if (sum > 0) {\n                right--;\n            } else {\n                result[*returnSize] = (int*)malloc(3 * sizeof(int));\n                result[*returnSize][0] = nums[i];\n                result[*returnSize][1] = nums[left];\n                result[*returnSize][2] = nums[right];\n                (*returnColumnSizes)[*returnSize] = 3;\n                (*returnSize)++;\n                while (left < right && nums[left] == nums[left+1]) left++;\n                while (left < right && nums[right] == nums[right-1]) right--;\n                left++;\n                right--;\n            }\n        }\n    }\n    return result;\n}');
INSERT INTO `solution` VALUES (16, 6, 1, 'def letterCombinations(digits):\n    if not digits: return []\n    phone = {\'2\': \'abc\', \'3\': \'def\', \'4\': \'ghi\', \'5\': \'jkl\', \'6\': \'mno\', \'7\': \'pqrs\', \'8\': \'tuv\', \'9\': \'wxyz\'}\n    result = []\n    def backtrack(index, path):\n        if len(path) == len(digits):\n            result.append(\'\' .join(path))\n            return\n        letters = phone[digits[index]]\n        for letter in letters:\n            path.append(letter)\n            backtrack(index + 1, path)\n            path.pop()\n    backtrack(0, [])\n    return result');
INSERT INTO `solution` VALUES (17, 6, 2, 'import java.util.ArrayList;\nimport java.util.HashMap;\nimport java.util.List;\nimport java.util.Map;\n\npublic class Solution {\n    public List<String> letterCombinations(String digits) {\n        List<String> result = new ArrayList<>();\n        if (digits == null || digits.length() == 0) return result;\n        Map<Character, String> phone = new HashMap<>();\n        phone.put(\'2\', \"abc\");\n        phone.put(\'3\', \"def\");\n        phone.put(\'4\', \"ghi\");\n        phone.put(\'5\', \"jkl\");\n        phone.put(\'6\', \"mno\");\n        phone.put(\'7\', \"pqrs\");\n        phone.put(\'8\', \"tuv\");\n        phone.put(\'9\', \"wxyz\");\n        backtrack(digits, 0, new StringBuilder(), result, phone);\n        return result;\n    }\n    private void backtrack(String digits, int index, StringBuilder path, List<String> result, Map<Character, String> phone) {\n        if (path.length() == digits.length()) {\n            result.add(path.toString());\n            return;\n        }\n        String letters = phone.get(digits.charAt(index));\n        for (char c : letters.toCharArray()) {\n            path.append(c);\n            backtrack(digits, index + 1, path, result, phone);\n            path.deleteCharAt(path.length() - 1);\n        }\n    }\n}');
INSERT INTO `solution` VALUES (18, 6, 3, '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nchar ** letterCombinations(char * digits, int* returnSize) {\n    *returnSize = 0;\n    if (digits[0] == \'\\0\') return NULL;\n    char *phone[] = {\"abc\", \"def\", \"ghi\", \"jkl\", \"mno\", \"pqrs\", \"tuv\", \"wxyz\"};\n    int len = strlen(digits);\n    int total = 1;\n    for (int i = 0; i < len; i++) {\n        int idx = digits[i] - \'2\';\n        total *= strlen(phone[idx]);\n    }\n    *returnSize = total;\n    char **result = (char **)malloc(total * sizeof(char *));\n    for (int i = 0; i < total; i++) {\n        result[i] = (char *)malloc((len + 1) * sizeof(char));\n        result[i][len] = \'\\0\';\n    }\n    int *indexes = (int *)calloc(len, sizeof(int));\n    for (int i = 0; i < total; i++) {\n        for (int j = 0; j < len; j++) {\n            int idx = digits[j] - \'2\';\n            result[i][j] = phone[idx][indexes[j]];\n        }\n        for (int j = len - 1; j >= 0; j--) {\n            int idx = digits[j] - \'2\';\n            indexes[j]++;\n            if (indexes[j] < strlen(phone[idx])) break;\n            indexes[j] = 0;\n        }\n    }\n    free(indexes);\n    return result;\n}');
INSERT INTO `solution` VALUES (19, 7, 1, 'def removeNthFromEnd(head, n):\n    dummy = ListNode(0)\n    dummy.next = head\n    first = dummy\n    second = dummy\n    # 第一个指针先走n+1步\n    for i in range(n + 1):\n        first = first.next\n    # 两个指针同时移动\n    while first:\n        first = first.next\n        second = second.next\n    # 删除节点\n    second.next = second.next.next\n    return dummy.next');
INSERT INTO `solution` VALUES (20, 7, 2, '/**\n * Definition for singly-linked list.\n * public class ListNode {\n *     int val;\n *     ListNode next;\n *     ListNode(int x) {\n *         val = x;\n *         next = null;\n *     }\n * }\n */\npublic class Solution {\n    public ListNode removeNthFromEnd(ListNode head, int n) {\n        ListNode dummy = new ListNode(0);\n        dummy.next = head;\n        ListNode first = dummy;\n        ListNode second = dummy;\n        // 第一个指针先走n+1步\n        for (int i = 0; i <= n; i++) {\n            first = first.next;\n        }\n        // 两个指针同时移动\n        while (first != null) {\n            first = first.next;\n            second = second.next;\n        }\n        // 删除节点\n        second.next = second.next.next;\n        return dummy.next;\n    }\n}');
INSERT INTO `solution` VALUES (21, 7, 3, '/**\n * Definition for singly-linked list.\n * struct ListNode {\n *     int val;\n *     struct ListNode *next;\n * };\n */\nstruct ListNode* removeNthFromEnd(struct ListNode* head, int n) {\n    struct ListNode* dummy = (struct ListNode*)malloc(sizeof(struct ListNode));\n    dummy->val = 0;\n    dummy->next = head;\n    struct ListNode* first = dummy;\n    struct ListNode* second = dummy;\n    // 第一个指针先走n+1步\n    for (int i = 0; i <= n; i++) {\n        first = first->next;\n    }\n    // 两个指针同时移动\n    while (first != NULL) {\n        first = first->next;\n        second = second->next;\n    }\n    // 删除节点\n    second->next = second->next->next;\n    struct ListNode* result = dummy->next;\n    free(dummy);\n    return result;\n}');
INSERT INTO `solution` VALUES (22, 8, 1, 'def isValid(s):\n    stack = []\n    mapping = {\")\": \"(\", \"}\": \"{\", \"]\": \"[\"}\n    for char in s:\n        if char in mapping:\n            top_element = stack.pop() if stack else \'#\'\n            if mapping[char] != top_element:\n                return False\n        else:\n            stack.append(char)\n    return not stack');
INSERT INTO `solution` VALUES (23, 8, 2, 'import java.util.Stack;\n\npublic class Solution {\n    public boolean isValid(String s) {\n        Stack<Character> stack = new Stack<>();\n        for (char c : s.toCharArray()) {\n            if (c == \'(\' || c == \'{\' || c == \'[\') {\n                stack.push(c);\n            } else {\n                if (stack.isEmpty()) return false;\n                char top = stack.pop();\n                if ((c == \')\' && top != \'(\') || (c == \'}\' && top != \'{\') || (c == \']\' && top != \'[\')) {\n                    return false;\n                }\n            }\n        }\n        return stack.isEmpty();\n    }\n}');
INSERT INTO `solution` VALUES (24, 8, 3, '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nbool isValid(char * s) {\n    int len = strlen(s);\n    if (len == 0) return true;\n    if (len % 2 != 0) return false;\n    char *stack = (char *)malloc(len * sizeof(char));\n    int top = -1;\n    for (int i = 0; i < len; i++) {\n        if (s[i] == \'(\' || s[i] == \'{\' || s[i] == \'[\') {\n            stack[++top] = s[i];\n        } else {\n            if (top == -1) return false;\n            char topChar = stack[top--];\n            if ((s[i] == \')\' && topChar != \'(\') || (s[i] == \'}\' && topChar != \'{\') || (s[i] == \']\' && topChar != \'[\')) {\n                free(stack);\n                return false;\n            }\n        }\n    }\n    bool result = (top == -1);\n    free(stack);\n    return result;\n}');
INSERT INTO `solution` VALUES (25, 9, 1, 'def mergeTwoLists(l1, l2):\n    dummy = ListNode(0)\n    current = dummy\n    while l1 and l2:\n        if l1.val < l2.val:\n            current.next = l1\n            l1 = l1.next\n        else:\n            current.next = l2\n            l2 = l2.next\n        current = current.next\n    current.next = l1 or l2\n    return dummy.next');
INSERT INTO `solution` VALUES (26, 9, 2, '/**\n * Definition for singly-linked list.\n * public class ListNode {\n *     int val;\n *     ListNode next;\n *     ListNode(int x) {\n *         val = x;\n *         next = null;\n *     }\n * }\n */\npublic class Solution {\n    public ListNode mergeTwoLists(ListNode l1, ListNode l2) {\n        ListNode dummy = new ListNode(0);\n        ListNode current = dummy;\n        while (l1 != null && l2 != null) {\n            if (l1.val < l2.val) {\n                current.next = l1;\n                l1 = l1.next;\n            } else {\n                current.next = l2;\n                l2 = l2.next;\n            }\n            current = current.next;\n        }\n        current.next = l1 != null ? l1 : l2;\n        return dummy.next;\n    }\n}');
INSERT INTO `solution` VALUES (27, 9, 3, '/**\n * Definition for singly-linked list.\n * struct ListNode {\n *     int val;\n *     struct ListNode *next;\n * };\n */\nstruct ListNode* mergeTwoLists(struct ListNode* l1, struct ListNode* l2) {\n    struct ListNode dummy = {0, NULL};\n    struct ListNode* current = &dummy;\n    while (l1 && l2) {\n        if (l1->val < l2->val) {\n            current->next = l1;\n            l1 = l1->next;\n        } else {\n            current->next = l2;\n            l2 = l2->next;\n        }\n        current = current->next;\n    }\n    current->next = l1 ? l1 : l2;\n    return dummy.next;\n}');
INSERT INTO `solution` VALUES (28, 10, 1, 'def generateParenthesis(n):\n    result = []\n    def backtrack(s, left, right):\n        if len(s) == 2 * n:\n            result.append(s)\n            return\n        if left < n:\n            backtrack(s+\'(\', left+1, right)\n        if right < left:\n            backtrack(s+\')\', left, right+1)\n    backtrack(\'\', 0, 0)\n    return result');
INSERT INTO `solution` VALUES (29, 10, 2, 'import java.util.ArrayList;\nimport java.util.List;\n\npublic class Solution {\n    public List<String> generateParenthesis(int n) {\n        List<String> result = new ArrayList<>();\n        backtrack(result, \"\", 0, 0, n);\n        return result;\n    }\n    private void backtrack(List<String> result, String current, int open, int close, int max) {\n        if (current.length() == max * 2) {\n            result.add(current);\n            return;\n        }\n        if (open < max) {\n            backtrack(result, current + \"(\", open + 1, close, max);\n        }\n        if (close < open) {\n            backtrack(result, current + \")\", open, close + 1, max);\n        }\n    }\n}');
INSERT INTO `solution` VALUES (30, 10, 3, '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nvoid backtrack(char** result, int* index, char* current, int open, int close, int max) {\n    int len = strlen(current);\n    if (len == max * 2) {\n        result[(*index)++] = strdup(current);\n        return;\n    }\n    if (open < max) {\n        current[len] = \'(\';\n        current[len + 1] = \'\\0\';\n        backtrack(result, index, current, open + 1, close, max);\n    }\n    if (close < open) {\n        current[len] = \')\';\n        current[len + 1] = \'\\0\';\n        backtrack(result, index, current, open, close + 1, max);\n    }\n}\n\nchar** generateParenthesis(int n, int* returnSize) {\n    int max_size = 1 << (2 * n); // 最大可能的组合数\n    char** result = (char**)malloc(max_size * sizeof(char*));\n    *returnSize = 0;\n    char* current = (char*)malloc((2 * n + 1) * sizeof(char));\n    current[0] = \'\\0\';\n    backtrack(result, returnSize, current, 0, 0, n);\n    free(current);\n    return result;\n}');
INSERT INTO `solution` VALUES (31, 11, 1, 'import heapq\n\ndef mergeKLists(lists):\n    dummy = ListNode(0)\n    current = dummy\n    heap = []\n    for i, node in enumerate(lists):\n        if node:\n            heapq.heappush(heap, (node.val, i, node))\n    while heap:\n        val, idx, node = heapq.heappop(heap)\n        current.next = node\n        current = current.next\n        if node.next:\n            heapq.heappush(heap, (node.next.val, idx, node.next))\n    return dummy.next');
INSERT INTO `solution` VALUES (32, 11, 2, 'import java.util.PriorityQueue;\n\n/**\n * Definition for singly-linked list.\n * public class ListNode {\n *     int val;\n *     ListNode next;\n *     ListNode(int x) {\n *         val = x;\n *         next = null;\n *     }\n * }\n */\npublic class Solution {\n    public ListNode mergeKLists(ListNode[] lists) {\n        if (lists == null || lists.length == 0) return null;\n        PriorityQueue<ListNode> heap = new PriorityQueue<>((a, b) -> a.val - b.val);\n        for (ListNode node : lists) {\n            if (node != null) {\n                heap.offer(node);\n            }\n        }\n        ListNode dummy = new ListNode(0);\n        ListNode current = dummy;\n        while (!heap.isEmpty()) {\n            ListNode minNode = heap.poll();\n            current.next = minNode;\n            current = current.next;\n            if (minNode.next != null) {\n                heap.offer(minNode.next);\n            }\n        }\n        return dummy.next;\n    }\n}');
INSERT INTO `solution` VALUES (33, 11, 3, '/**\n * Definition for singly-linked list.\n * struct ListNode {\n *     int val;\n *     struct ListNode *next;\n * };\n */\nstruct ListNode* mergeKLists(struct ListNode** lists, int listsSize) {\n    if (listsSize == 0) return NULL;\n    struct ListNode dummy = {0, NULL};\n    struct ListNode* current = &dummy;\n    int empty = 1;\n    do {\n        empty = 1;\n        int minIndex = -1;\n        struct ListNode* minNode = NULL;\n        for (int i = 0; i < listsSize; i++) {\n            if (lists[i] != NULL) {\n                empty = 0;\n                if (minNode == NULL || lists[i]->val < minNode->val) {\n                    minNode = lists[i];\n                    minIndex = i;\n                }\n            }\n        }\n        if (!empty) {\n            current->next = minNode;\n            current = current->next;\n            lists[minIndex] = lists[minIndex]->next;\n        }\n    } while (!empty);\n    return dummy.next;\n}');
INSERT INTO `solution` VALUES (34, 12, 1, 'def nextPermutation(nums):\n    i = len(nums) - 2\n    while i >= 0 and nums[i] >= nums[i+1]:\n        i -= 1\n    if i >= 0:\n        j = len(nums) - 1\n        while j > i and nums[j] <= nums[i]:\n            j -= 1\n        nums[i], nums[j] = nums[j], nums[i]\n    left, right = i + 1, len(nums) - 1\n    while left < right:\n        nums[left], nums[right] = nums[right], nums[left]\n        left += 1\n        right -= 1');
INSERT INTO `solution` VALUES (35, 12, 2, 'public class Solution {\n    public void nextPermutation(int[] nums) {\n        int i = nums.length - 2;\n        while (i >= 0 && nums[i] >= nums[i + 1]) {\n            i--;\n        }\n        if (i >= 0) {\n            int j = nums.length - 1;\n            while (j > i && nums[j] <= nums[i]) {\n                j--;\n            }\n            swap(nums, i, j);\n        }\n        reverse(nums, i + 1);\n    }\n    private void swap(int[] nums, int i, int j) {\n        int temp = nums[i];\n        nums[i] = nums[j];\n        nums[j] = temp;\n    }\n    private void reverse(int[] nums, int start) {\n        int i = start, j = nums.length - 1;\n        while (i < j) {\n            swap(nums, i, j);\n            i++;\n            j--;\n        }\n    }\n}');
INSERT INTO `solution` VALUES (36, 12, 3, '#include <stdio.h>\n\nvoid nextPermutation(int* nums, int numsSize) {\n    int i = numsSize - 2;\n    while (i >= 0 && nums[i] >= nums[i + 1]) {\n        i--;\n    }\n    if (i >= 0) {\n        int j = numsSize - 1;\n        while (j > i && nums[j] <= nums[i]) {\n            j--;\n        }\n        int temp = nums[i];\n        nums[i] = nums[j];\n        nums[j] = temp;\n    }\n    int left = i + 1, right = numsSize - 1;\n    while (left < right) {\n        int temp = nums[left];\n        nums[left] = nums[right];\n        nums[right] = temp;\n        left++;\n        right--;\n    }\n}');
INSERT INTO `solution` VALUES (37, 13, 1, 'def longestValidParentheses(s):\n    max_len = 0\n    stack = [-1]\n    for i in range(len(s)):\n        if s[i] == \'(\':\n            stack.append(i)\n        else:\n            stack.pop()\n            if not stack:\n                stack.append(i)\n            else:\n                current_len = i - stack[-1]\n                max_len = max(max_len, current_len)\n    return max_len');
INSERT INTO `solution` VALUES (38, 13, 2, 'public class Solution {\n    public int longestValidParentheses(String s) {\n        int maxLen = 0;\n        java.util.Stack<Integer> stack = new java.util.Stack<>();\n        stack.push(-1);\n        for (int i = 0; i < s.length(); i++) {\n            if (s.charAt(i) == \'(\') {\n                stack.push(i);\n            } else {\n                stack.pop();\n                if (stack.isEmpty()) {\n                    stack.push(i);\n                } else {\n                    maxLen = Math.max(maxLen, i - stack.peek());\n                }\n            }\n        }\n        return maxLen;\n    }\n}');
INSERT INTO `solution` VALUES (39, 13, 3, '#include <stdio.h>\n#include <stdlib.h>\n\nint longestValidParentheses(char * s) {\n    int len = strlen(s);\n    if (len == 0) return 0;\n    int *stack = (int *)malloc((len + 1) * sizeof(int));\n    int top = -1;\n    stack[++top] = -1;\n    int max_len = 0;\n    for (int i = 0; i < len; i++) {\n        if (s[i] == \'(\') {\n            stack[++top] = i;\n        } else {\n            top--;\n            if (top == -1) {\n                stack[++top] = i;\n            } else {\n                int current_len = i - stack[top];\n                if (current_len > max_len) {\n                    max_len = current_len;\n                }\n            }\n        }\n    }\n    free(stack);\n    return max_len;\n}');
INSERT INTO `solution` VALUES (40, 14, 1, 'def search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[left] <= nums[mid]:\n            if nums[left] <= target < nums[mid]:\n                right = mid - 1\n            else:\n                left = mid + 1\n        else:\n            if nums[mid] < target <= nums[right]:\n                left = mid + 1\n            else:\n                right = mid - 1\n    return -1');
INSERT INTO `solution` VALUES (41, 14, 2, 'public class Solution {\n    public int search(int[] nums, int target) {\n        int left = 0, right = nums.length - 1;\n        while (left <= right) {\n            int mid = left + (right - left) / 2;\n            if (nums[mid] == target) {\n                return mid;\n            }\n            if (nums[left] <= nums[mid]) {\n                if (nums[left] <= target && target < nums[mid]) {\n                    right = mid - 1;\n                } else {\n                    left = mid + 1;\n                }\n            } else {\n                if (nums[mid] < target && target <= nums[right]) {\n                    left = mid + 1;\n                } else {\n                    right = mid - 1;\n                }\n            }\n        }\n        return -1;\n    }\n}');
INSERT INTO `solution` VALUES (42, 14, 3, '#include <stdio.h>\n\nint search(int* nums, int numsSize, int target) {\n    int left = 0, right = numsSize - 1;\n    while (left <= right) {\n        int mid = left + (right - left) / 2;\n        if (nums[mid] == target) {\n            return mid;\n        }\n        if (nums[left] <= nums[mid]) {\n            if (nums[left] <= target && target < nums[mid]) {\n                right = mid - 1;\n            } else {\n                left = mid + 1;\n            }\n        } else {\n            if (nums[mid] < target && target <= nums[right]) {\n                left = mid + 1;\n            } else {\n                right = mid - 1;\n            }\n        }\n    }\n    return -1;\n}');
INSERT INTO `solution` VALUES (43, 15, 1, 'def combinationSum(candidates, target):\n    result = []\n    def backtrack(remain, combo, start):\n        if remain == 0:\n            result.append(list(combo))\n            return\n        elif remain < 0:\n            return\n        for i in range(start, len(candidates)):\n            combo.append(candidates[i])\n            backtrack(remain - candidates[i], combo, i)\n            combo.pop()\n    backtrack(target, [], 0)\n    return result');
INSERT INTO `solution` VALUES (44, 15, 2, 'import java.util.ArrayList;\nimport java.util.List;\n\npublic class Solution {\n    public List<List<Integer>> combinationSum(int[] candidates, int target) {\n        List<List<Integer>> result = new ArrayList<>();\n        backtrack(candidates, target, 0, new ArrayList<>(), result);\n        return result;\n    }\n    private void backtrack(int[] candidates, int remain, int start, List<Integer> combo, List<List<Integer>> result) {\n        if (remain == 0) {\n            result.add(new ArrayList<>(combo));\n            return;\n        } else if (remain < 0) {\n            return;\n        }\n        for (int i = start; i < candidates.length; i++) {\n            combo.add(candidates[i]);\n            backtrack(candidates, remain - candidates[i], i, combo, result);\n            combo.remove(combo.size() - 1);\n        }\n    }\n}');
INSERT INTO `solution` VALUES (45, 15, 3, '#include <stdio.h>\n#include <stdlib.h>\n\nvoid backtrack(int* candidates, int candidatesSize, int target, int start, int* combo, int comboSize, int*** result, int* returnSize, int** returnColumnSizes) {\n    if (target == 0) {\n        (*result)[*returnSize] = (int*)malloc(comboSize * sizeof(int));\n        memcpy((*result)[*returnSize], combo, comboSize * sizeof(int));\n        (*returnColumnSizes)[*returnSize] = comboSize;\n        (*returnSize)++;\n        return;\n    }\n    for (int i = start; i < candidatesSize; i++) {\n        if (candidates[i] <= target) {\n            combo[comboSize] = candidates[i];\n            backtrack(candidates, candidatesSize, target - candidates[i], i, combo, comboSize + 1, result, returnSize, returnColumnSizes);\n        }\n    }\n}\n\nint** combinationSum(int* candidates, int candidatesSize, int target, int* returnSize, int** returnColumnSizes) {\n    int max_size = 1000;\n    int** result = (int**)malloc(max_size * sizeof(int*));\n    *returnColumnSizes = (int*)malloc(max_size * sizeof(int));\n    *returnSize = 0;\n    int* combo = (int*)malloc(target * sizeof(int));\n    backtrack(candidates, candidatesSize, target, 0, combo, 0, &result, returnSize, returnColumnSizes);\n    free(combo);\n    return result;\n}');
INSERT INTO `solution` VALUES (46, 16, 1, 'def rotate(matrix):\n    n = len(matrix)\n    for i in range(n):\n        for j in range(i, n):\n            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n    for i in range(n):\n        matrix[i] = matrix[i][::-1]');
INSERT INTO `solution` VALUES (47, 16, 2, 'public class Solution {\n    public void rotate(int[][] matrix) {\n        int n = matrix.length;\n        // 转置矩阵\n        for (int i = 0; i < n; i++) {\n            for (int j = i; j < n; j++) {\n                int temp = matrix[i][j];\n                matrix[i][j] = matrix[j][i];\n                matrix[j][i] = temp;\n            }\n        }\n        // 反转每一行\n        for (int i = 0; i < n; i++) {\n            for (int j = 0; j < n / 2; j++) {\n                int temp = matrix[i][j];\n                matrix[i][j] = matrix[i][n - j - 1];\n                matrix[i][n - j - 1] = temp;\n            }\n        }\n    }\n}');
INSERT INTO `solution` VALUES (48, 16, 3, '#include <stdio.h>\n\nvoid rotate(int** matrix, int matrixSize, int* matrixColSize) {\n    // 转置矩阵\n    for (int i = 0; i < matrixSize; i++) {\n        for (int j = i; j < matrixSize; j++) {\n            int temp = matrix[i][j];\n            matrix[i][j] = matrix[j][i];\n            matrix[j][i] = temp;\n        }\n    }\n    // 反转每一行\n    for (int i = 0; i < matrixSize; i++) {\n        for (int j = 0; j < matrixSize / 2; j++) {\n            int temp = matrix[i][j];\n            matrix[i][j] = matrix[i][matrixSize - j - 1];\n            matrix[i][matrixSize - j - 1] = temp;\n        }\n    }\n}');
INSERT INTO `solution` VALUES (49, 17, 1, 'from collections import defaultdict\n\ndef groupAnagrams(strs):\n    result = defaultdict(list)\n    for s in strs:\n        count = [0] * 26\n        for c in s:\n            count[ord(c) - ord(\'a\')] += 1\n        result[tuple(count)].append(s)\n    return list(result.values())');
INSERT INTO `solution` VALUES (50, 17, 2, 'import java.util.ArrayList;\nimport java.util.Arrays;\nimport java.util.HashMap;\nimport java.util.List;\nimport java.util.Map;\n\npublic class Solution {\n    public List<List<String>> groupAnagrams(String[] strs) {\n        Map<String, List<String>> map = new HashMap<>();\n        for (String s : strs) {\n            char[] chars = s.toCharArray();\n            Arrays.sort(chars);\n            String key = new String(chars);\n            if (!map.containsKey(key)) {\n                map.put(key, new ArrayList<>());\n            }\n            map.get(key).add(s);\n        }\n        return new ArrayList<>(map.values());\n    }\n}');
INSERT INTO `solution` VALUES (51, 17, 3, '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n// 比较函数用于qsort\nint compare(const void *a, const void *b) {\n    return (*(char*)a - *(char*)b);\n}\n\nchar *** groupAnagrams(char ** strs, int strsSize, int* returnSize, int** returnColumnSizes) {\n    if (strsSize == 0) {\n        *returnSize = 0;\n        return NULL;\n    }\n    // 假设最多有strsSize个不同的组\n    char ***result = (char***)malloc(strsSize * sizeof(char**));\n    *returnColumnSizes = (int*)malloc(strsSize * sizeof(int));\n    int *capacities = (int*)malloc(strsSize * sizeof(int));\n    char **keys = (char**)malloc(strsSize * sizeof(char*));\n    *returnSize = 0;\n    for (int i = 0; i < strsSize; i++) {\n        int len = strlen(strs[i]);\n        char *key = (char*)malloc((len + 1) * sizeof(char));\n        strcpy(key, strs[i]);\n        qsort(key, len, sizeof(char), compare);\n        int found = 0;\n        for (int j = 0; j < *returnSize; j++) {\n            if (strcmp(keys[j], key) == 0) {\n                if ((*returnColumnSizes)[j] >= capacities[j]) {\n                    capacities[j] *= 2;\n                    result[j] = (char**)realloc(result[j], capacities[j] * sizeof(char*));\n                }\n                result[j][(*returnColumnSizes)[j]++] = strs[i];\n                found = 1;\n                free(key);\n                break;\n            }\n        }\n        if (!found) {\n            keys[*returnSize] = key;\n            capacities[*returnSize] = 10;\n            result[*returnSize] = (char**)malloc(capacities[*returnSize] * sizeof(char*));\n            result[*returnSize][0] = strs[i];\n            (*returnColumnSizes)[*returnSize] = 1;\n            (*returnSize)++;\n        }\n    }\n    free(capacities);\n    free(keys);\n    return result;\n}');
INSERT INTO `solution` VALUES (52, 18, 1, 'def maxSubArray(nums):\n    if not nums:\n        return 0\n    current_sum = max_sum = nums[0]\n    for num in nums[1:]:\n        current_sum = max(num, current_sum + num)\n        max_sum = max(max_sum, current_sum)\n    return max_sum');
INSERT INTO `solution` VALUES (53, 18, 2, 'public class Solution {\n    public int maxSubArray(int[] nums) {\n        if (nums == null || nums.length == 0) return 0;\n        int currentSum = nums[0];\n        int maxSum = nums[0];\n        for (int i = 1; i < nums.length; i++) {\n            currentSum = Math.max(nums[i], currentSum + nums[i]);\n            maxSum = Math.max(maxSum, currentSum);\n        }\n        return maxSum;\n    }\n}');
INSERT INTO `solution` VALUES (54, 18, 3, '#include <stdio.h>\n\nint maxSubArray(int* nums, int numsSize) {\n    if (numsSize == 0) return 0;\n    int current_sum = nums[0];\n    int max_sum = nums[0];\n    for (int i = 1; i < numsSize; i++) {\n        if (nums[i] > current_sum + nums[i]) {\n            current_sum = nums[i];\n        } else {\n            current_sum += nums[i];\n        }\n        if (current_sum > max_sum) {\n            max_sum = current_sum;\n        }\n    }\n    return max_sum;\n}');
INSERT INTO `solution` VALUES (55, 19, 1, 'def canJump(nums):\n    max_reach = 0\n    for i in range(len(nums)):\n        if i > max_reach:\n            return False\n        max_reach = max(max_reach, i + nums[i])\n    return True');
INSERT INTO `solution` VALUES (56, 19, 2, 'public class Solution {\n    public boolean canJump(int[] nums) {\n        int maxReach = 0;\n        for (int i = 0; i < nums.length; i++) {\n            if (i > maxReach) return false;\n            maxReach = Math.max(maxReach, i + nums[i]);\n        }\n        return true;\n    }\n}');
INSERT INTO `solution` VALUES (57, 19, 3, '#include <stdio.h>\n#include <stdbool.h>\n\nbool canJump(int* nums, int numsSize) {\n    int max_reach = 0;\n    for (int i = 0; i < numsSize; i++) {\n        if (i > max_reach) {\n            return false;\n        }\n        if (i + nums[i] > max_reach) {\n            max_reach = i + nums[i];\n        }\n    }\n    return true;\n}');
INSERT INTO `solution` VALUES (58, 20, 1, 'def merge(intervals):\n    if not intervals:\n        return []\n    intervals.sort(key=lambda x: x[0])\n    merged = [intervals[0]]\n    for interval in intervals[1:]:\n        last = merged[-1]\n        if interval[0] <= last[1]:\n            merged[-1] = [last[0], max(last[1], interval[1])]\n        else:\n            merged.append(interval)\n    return merged');
INSERT INTO `solution` VALUES (59, 20, 2, 'import java.util.Arrays;\nimport java.util.LinkedList;\n\npublic class Solution {\n    public int[][] merge(int[][] intervals) {\n        if (intervals.length <= 1) return intervals;\n        Arrays.sort(intervals, (a, b) -> Integer.compare(a[0], b[0]));\n        LinkedList<int[]> merged = new LinkedList<>();\n        for (int[] interval : intervals) {\n            if (merged.isEmpty() || merged.getLast()[1] < interval[0]) {\n                merged.add(interval);\n            } else {\n                merged.getLast()[1] = Math.max(merged.getLast()[1], interval[1]);\n            }\n        }\n        return merged.toArray(new int[merged.size()][]);\n    }\n}');
INSERT INTO `solution` VALUES (60, 20, 3, '#include <stdio.h>\n#include <stdlib.h>\n\n// 比较函数用于qsort\nint compare(const void *a, const void *b) {\n    return ((int*)a)[0] - ((int*)b)[0];\n}\n\nint** merge(int** intervals, int intervalsSize, int* returnSize, int** returnColumnSizes) {\n    if (intervalsSize == 0) {\n        *returnSize = 0;\n        return NULL;\n    }\n    // 排序区间\n    qsort(intervals, intervalsSize, sizeof(int*), compare);\n    // 分配最大可能的空间\n    int** result = (int**)malloc(intervalsSize * sizeof(int*));\n    *returnColumnSizes = (int*)malloc(intervalsSize * sizeof(int));\n    int count = 0;\n    result[0] = (int*)malloc(2 * sizeof(int));\n    result[0][0] = intervals[0][0];\n    result[0][1] = intervals[0][1];\n    (*returnColumnSizes)[0] = 2;\n    count++;\n    for (int i = 1; i < intervalsSize; i++) {\n        int last = count - 1;\n        if (intervals[i][0] <= result[last][1]) {\n            // 合并区间\n            if (intervals[i][1] > result[last][1]) {\n                result[last][1] = intervals[i][1];\n            }\n        } else {\n            // 添加新区间\n            result[count] = (int*)malloc(2 * sizeof(int));\n            result[count][0] = intervals[i][0];\n            result[count][1] = intervals[i][1];\n            (*returnColumnSizes)[count] = 2;\n            count++;\n        }\n    }\n    *returnSize = count;\n    return result;\n}');
INSERT INTO `solution` VALUES (61, 21, 1, 'def uniquePaths(m, n):\n    dp = [[1 for _ in range(n)] for _ in range(m)]\n    for i in range(1, m):\n        for j in range(1, n):\n            dp[i][j] = dp[i-1][j] + dp[i][j-1]\n    return dp[-1][-1]');
INSERT INTO `solution` VALUES (62, 21, 2, 'public class Solution {\n    public int uniquePaths(int m, int n) {\n        int[][] dp = new int[m][n];\n        for (int i = 0; i < m; i++) {\n            dp[i][0] = 1;\n        }\n        for (int j = 0; j < n; j++) {\n            dp[0][j] = 1;\n        }\n        for (int i = 1; i < m; i++) {\n            for (int j = 1; j < n; j++) {\n                dp[i][j] = dp[i-1][j] + dp[i][j-1];\n            }\n        }\n        return dp[m-1][n-1];\n    }\n}');
INSERT INTO `solution` VALUES (63, 21, 3, '#include <stdio.h>\n\nint uniquePaths(int m, int n) {\n    int dp[m][n];\n    for (int i = 0; i < m; i++) {\n        dp[i][0] = 1;\n    }\n    for (int j = 0; j < n; j++) {\n        dp[0][j] = 1;\n    }\n    for (int i = 1; i < m; i++) {\n        for (int j = 1; j < n; j++) {\n            dp[i][j] = dp[i-1][j] + dp[i][j-1];\n        }\n    }\n    return dp[m-1][n-1];\n}');
INSERT INTO `solution` VALUES (64, 22, 1, 'def minPathSum(grid):\n    m, n = len(grid), len(grid[0])\n    for i in range(m):\n        for j in range(n):\n            if i == 0 and j == 0:\n                continue\n            elif i == 0:\n                grid[i][j] += grid[i][j-1]\n            elif j == 0:\n                grid[i][j] += grid[i-1][j]\n            else:\n                grid[i][j] += min(grid[i-1][j], grid[i][j-1])\n    return grid[-1][-1]');
INSERT INTO `solution` VALUES (65, 22, 2, 'public class Solution {\n    public int minPathSum(int[][] grid) {\n        int m = grid.length;\n        int n = grid[0].length;\n        for (int i = 0; i < m; i++) {\n            for (int j = 0; j < n; j++) {\n                if (i == 0 && j == 0) continue;\n                else if (i == 0) grid[i][j] += grid[i][j-1];\n                else if (j == 0) grid[i][j] += grid[i-1][j];\n                else grid[i][j] += Math.min(grid[i-1][j], grid[i][j-1]);\n            }\n        }\n        return grid[m-1][n-1];\n    }\n}');
INSERT INTO `solution` VALUES (66, 22, 3, '#include <stdio.h>\n\nint minPathSum(int** grid, int gridSize, int* gridColSize) {\n    int m = gridSize;\n    int n = gridColSize[0];\n    for (int i = 0; i < m; i++) {\n        for (int j = 0; j < n; j++) {\n            if (i == 0 && j == 0) continue;\n            else if (i == 0) grid[i][j] += grid[i][j-1];\n            else if (j == 0) grid[i][j] += grid[i-1][j];\n            else grid[i][j] += (grid[i-1][j] < grid[i][j-1] ? grid[i-1][j] : grid[i][j-1]);\n        }\n    }\n    return grid[m-1][n-1];\n}');
INSERT INTO `solution` VALUES (67, 23, 1, 'def mergeKLists(lists):\n    if not lists:\n        return None\n    return self.merge_range_lists(lists, 0, len(lists) - 1)\n\n    def merge_range_lists(lists, start, end):\n        if start == end:\n            return lists[start]\n        mid = (start + end) // 2\n        left = self.merge_range_lists(lists, start, mid)\n        right = self.merge_range_lists(lists, mid + 1, end)\n        return self.merge_two_lists(left, right)\n\n    def merge_two_lists(self, l1, l2):\n        dummy = ListNode(0)\n        tail = dummy\n        while l1 and l2:\n            if l1.val < l2.val:\n                tail.next = l1\n                l1 = l1.next\n            else:\n                tail.next = l2\n                l2 = l2.next\n            tail = tail.next\n        tail.next = l1 or l2\n        return dummy.next');
INSERT INTO `solution` VALUES (68, 23, 2, 'public class Solution {\n    public ListNode mergeKLists(ListNode[] lists) {\n        if (lists == null || lists.length == 0) return null;\n        return mergeRange(lists, 0, lists.length - 1);\n    }\n    private ListNode mergeRange(ListNode[] lists, int start, int end) {\n        if (start == end) return lists[start];\n        int mid = (start + end) / 2;\n        ListNode left = mergeRange(lists, start, mid);\n        ListNode right = mergeRange(lists, mid + 1, end);\n        return mergeTwoLists(left, right);\n    }\n    private ListNode mergeTwoLists(ListNode l1, ListNode l2) {\n        ListNode dummy = new ListNode(0);\n        ListNode tail = dummy;\n        while (l1 != null && l2 != null) {\n            if (l1.val < l2.val) {\n                tail.next = l1;\n                l1 = l1.next;\n            } else {\n                tail.next = l2;\n                l2 = l2.next;\n            }\n            tail = tail.next;\n        }\n        tail.next = (l1 != null) ? l1 : l2;\n        return dummy.next;\n    }\n}');
INSERT INTO `solution` VALUES (69, 23, 3, '#include <stdio.h>\n#include <stdlib.h>\n\nstruct ListNode {\n    int val;\n    struct ListNode *next;\n};\n\nstruct ListNode* mergeTwoLists(struct ListNode* l1, struct ListNode* l2) {\n    struct ListNode dummy = {0, NULL};\n    struct ListNode* tail = &dummy;\n    while (l1 && l2) {\n        if (l1->val < l2->val) {\n            tail->next = l1;\n            l1 = l1->next;\n        } else {\n            tail->next = l2;\n            l2 = l2->next;\n        }\n        tail = tail->next;\n    }\n    tail->next = l1 ? l1 : l2;\n    return dummy.next;\n}\n\nstruct ListNode* mergeKLists(struct ListNode** lists, int listsSize) {\n    if (listsSize == 0) return NULL;\n    for (int step = 1; step < listsSize; step *= 2) {\n        for (int i = 0; i + step < listsSize; i += 2 * step) {\n            lists[i] = mergeTwoLists(lists[i], lists[i + step]);\n        }\n    }\n    return lists[0];\n}');
INSERT INTO `solution` VALUES (70, 24, 1, 'def nextPermutation(nums):\n    i = len(nums) - 2\n    while i >= 0 and nums[i] >= nums[i+1]:\n        i -= 1\n    if i >= 0:\n        j = len(nums) - 1\n        while j > i and nums[j] <= nums[i]:\n            j -= 1\n        nums[i], nums[j] = nums[j], nums[i]\n    left, right = i + 1, len(nums) - 1\n    while left < right:\n        nums[left], nums[right] = nums[right], nums[left]\n        left += 1\n        right -= 1');
INSERT INTO `solution` VALUES (71, 24, 2, 'public class Solution {\n    public void nextPermutation(int[] nums) {\n        int i = nums.length - 2;\n        while (i >= 0 && nums[i] >= nums[i + 1]) {\n            i--;\n        }\n        if (i >= 0) {\n            int j = nums.length - 1;\n            while (j > i && nums[j] <= nums[i]) {\n                j--;\n            }\n            swap(nums, i, j);\n        }\n        reverse(nums, i + 1);\n    }\n    private void swap(int[] nums, int i, int j) {\n        int temp = nums[i];\n        nums[i] = nums[j];\n        nums[j] = temp;\n    }\n    private void reverse(int[] nums, int start) {\n        int i = start, j = nums.length - 1;\n        while (i < j) {\n            swap(nums, i, j);\n            i++;\n            j--;\n        }\n    }\n}');
INSERT INTO `solution` VALUES (72, 24, 3, '#include <stdio.h>\n\nvoid nextPermutation(int* nums, int numsSize) {\n    int i = numsSize - 2;\n    while (i >= 0 && nums[i] >= nums[i + 1]) {\n        i--;\n    }\n    if (i >= 0) {\n        int j = numsSize - 1;\n        while (j > i && nums[j] <= nums[i]) {\n            j--;\n        }\n        int temp = nums[i];\n        nums[i] = nums[j];\n        nums[j] = temp;\n    }\n    int left = i + 1, right = numsSize - 1;\n    while (left < right) {\n        int temp = nums[left];\n        nums[left] = nums[right];\n        nums[right] = temp;\n        left++;\n        right--;\n    }\n}');
INSERT INTO `solution` VALUES (73, 25, 1, 'def search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[left] <= nums[mid]:\n            if nums[left] <= target < nums[mid]:\n                right = mid - 1\n            else:\n                left = mid + 1\n        else:\n            if nums[mid] < target <= nums[right]:\n                left = mid + 1\n            else:\n                right = mid - 1\n    return -1');
INSERT INTO `solution` VALUES (74, 25, 2, 'public class Solution {\n    public int search(int[] nums, int target) {\n        int left = 0, right = nums.length - 1;\n        while (left <= right) {\n            int mid = left + (right - left) / 2;\n            if (nums[mid] == target) return mid;\n            if (nums[left] <= nums[mid]) {\n                if (nums[left] <= target && target < nums[mid]) {\n                    right = mid - 1;\n                } else {\n                    left = mid + 1;\n                }\n            } else {\n                if (nums[mid] < target && target <= nums[right]) {\n                    left = mid + 1;\n                } else {\n                    right = mid - 1;\n                }\n            }\n        }\n        return -1;\n    }\n}');
INSERT INTO `solution` VALUES (75, 25, 3, '#include <stdio.h>\n\nint search(int* nums, int numsSize, int target) {\n    int left = 0, right = numsSize - 1;\n    while (left <= right) {\n        int mid = left + (right - left) / 2;\n        if (nums[mid] == target) return mid;\n        if (nums[left] <= nums[mid]) {\n            if (target >= nums[left] && target < nums[mid]) {\n                right = mid - 1;\n            } else {\n                left = mid + 1;\n            }\n        } else {\n            if (target > nums[mid] && target <= nums[right]) {\n                left = mid + 1;\n            } else {\n                right = mid - 1;\n            }\n        }\n    }\n    return -1;\n}');
INSERT INTO `solution` VALUES (76, 26, 1, 'def removeDuplicates(nums):\n    if not nums:\n        return 0\n    i = 0\n    for j in range(1, len(nums)):\n        if nums[j] != nums[i]:\n            i += 1\n            nums[i] = nums[j]\n    return i + 1');
INSERT INTO `solution` VALUES (77, 26, 2, 'public class Solution {\n    public int removeDuplicates(int[] nums) {\n        if (nums.length == 0) return 0;\n        int i = 0;\n        for (int j = 1; j < nums.length; j++) {\n            if (nums[j] != nums[i]) {\n                i++;\n                nums[i] = nums[j];\n            }\n        }\n        return i + 1;\n    }\n}');
INSERT INTO `solution` VALUES (78, 26, 3, '#include <stdio.h>\n\nint removeDuplicates(int* nums, int numsSize) {\n    if (numsSize == 0) return 0;\n    int i = 0;\n    for (int j = 1; j < numsSize; j++) {\n        if (nums[j] != nums[i]) {\n            i++;\n            nums[i] = nums[j];\n        }\n    }\n    return i + 1;\n}');
INSERT INTO `solution` VALUES (79, 27, 1, 'def maxProfit(prices):\n    min_price = float(\'inf\')\n    max_profit = 0\n    for price in prices:\n        min_price = min(min_price, price)\n        profit = price - min_price\n        max_profit = max(max_profit, profit)\n    return max_profit');
INSERT INTO `solution` VALUES (80, 27, 2, 'public class Solution {\n    public int maxProfit(int[] prices) {\n        if (prices.length == 0) return 0;\n        int minPrice = Integer.MAX_VALUE;\n        int maxProfit = 0;\n        for (int price : prices) {\n            minPrice = Math.min(minPrice, price);\n            maxProfit = Math.max(maxProfit, price - minPrice);\n        }\n        return maxProfit;\n    }\n}');
INSERT INTO `solution` VALUES (81, 27, 3, '#include <stdio.h>\n#include <stdlib.h>\n\nint maxProfit(int* prices, int pricesSize) {\n    if (pricesSize == 0) return 0;\n    int min_price = prices[0];\n    int max_profit = 0;\n    for (int i = 1; i < pricesSize; i++) {\n        if (prices[i] < min_price) {\n            min_price = prices[i];\n        } else if (prices[i] - min_price > max_profit) {\n            max_profit = prices[i] - min_price;\n        }\n    }\n    return max_profit;\n}');
INSERT INTO `solution` VALUES (82, 28, 1, 'def strStr(haystack, needle):\n    if needle == \"\":\n        return 0\n    n, m = len(haystack), len(needle)\n    for i in range(n - m + 1):\n        if haystack[i:i+m] == needle:\n            return i\n    return -1');
INSERT INTO `solution` VALUES (83, 28, 2, 'public class Solution {\n    public int strStr(String haystack, String needle) {\n        if (needle.isEmpty()) return 0;\n        int n = haystack.length(), m = needle.length();\n        for (int i = 0; i <= n - m; i++) {\n            if (haystack.substring(i, i + m).equals(needle)) {\n                return i;\n            }\n        }\n        return -1;\n    }\n}');
INSERT INTO `solution` VALUES (84, 28, 3, '#include <stdio.h>\n#include <string.h>\n\nint strStr(char * haystack, char * needle) {\n    if (*needle == \'\\0\') return 0;\n    int n = strlen(haystack), m = strlen(needle);\n    for (int i = 0; i <= n - m; i++) {\n        if (strncmp(haystack + i, needle, m) == 0) {\n            return i;\n        }\n    }\n    return -1;\n}');
INSERT INTO `solution` VALUES (85, 29, 1, 'def divide(dividend, divisor):\n    INT_MAX = (1 << 31) - 1\n    INT_MIN = - (1 << 31)\n    if dividend == INT_MIN and divisor == -1:\n        return INT_MAX\n    sign = (dividend > 0) ^ (divisor > 0)\n    dividend = abs(dividend)\n    divisor = abs(divisor)\n    res = 0\n    while dividend >= divisor:\n        temp, multiple = divisor, 1\n        while dividend >= (temp << 1):\n            temp <<= 1\n            multiple <<= 1\n        dividend -= temp\n        res += multiple\n    return -res if sign else res');
INSERT INTO `solution` VALUES (86, 29, 2, 'public class Solution {\n    public int divide(int dividend, int divisor) {\n        if (dividend == Integer.MIN_VALUE && divisor == -1) {\n            return Integer.MAX_VALUE;\n        }\n        int sign = (dividend > 0) ^ (divisor > 0) ? -1 : 1;\n        long dvd = Math.abs((long)dividend);\n        long dvs = Math.abs((long)divisor);\n        int res = 0;\n        while (dvd >= dvs) {\n            long temp = dvs, multiple = 1;\n            while (dvd >= (temp << 1)) {\n                temp <<= 1;\n                multiple <<= 1;\n            }\n            dvd -= temp;\n            res += multiple;\n        }\n        return sign * res;\n    }\n}');
INSERT INTO `solution` VALUES (87, 29, 3, '#include <stdio.h>\n#include <stdlib.h>\n#include <limits.h>\n\nint divide(int dividend, int divisor) {\n    if (dividend == INT_MIN && divisor == -1) {\n        return INT_MAX;\n    }\n    int sign = ((dividend < 0) ^ (divisor < 0)) ? -1 : 1;\n    long long dvd = labs(dividend);\n    long long dvs = labs(divisor);\n    int res = 0;\n    while (dvd >= dvs) {\n        long long temp = dvs, multiple = 1;\n        while (dvd >= (temp << 1)) {\n            temp <<= 1;\n            multiple <<= 1;\n        }\n        dvd -= temp;\n        res += multiple;\n    }\n    return sign * res;\n}');
INSERT INTO `solution` VALUES (88, 30, 1, 'def findSubstring(s, words):\n    if not s or not words:\n        return []\n    word_len = len(words[0])\n    total_len = word_len * len(words)\n    result = []\n    word_count = {word: words.count(word) for word in set(words)}\n    for i in range(len(s) - total_len + 1):\n        temp_count = word_count.copy()\n        j = 0\n        while j < total_len:\n            word = s[i + j:i + j + word_len]\n            if word in temp_count and temp_count[word] > 0:\n                temp_count[word] -= 1\n                j += word_len\n            else:\n                break\n        if j == total_len:\n            result.append(i)\n    return result');
INSERT INTO `solution` VALUES (89, 30, 2, 'import java.util.ArrayList;\nimport java.util.HashMap;\nimport java.util.List;\nimport java.util.Map;\n\npublic class Solution {\n    public List<Integer> findSubstring(String s, String[] words) {\n        List<Integer> result = new ArrayList<>();\n        if (s == null || s.length() == 0 || words == null || words.length == 0) {\n            return result;\n        }\n        int wordLen = words[0].length();\n        int totalLen = wordLen * words.length;\n        Map<String, Integer> wordCount = new HashMap<>();\n        for (String word : words) {\n            wordCount.put(word, wordCount.getOrDefault(word, 0) + 1);\n        }\n        for (int i = 0; i <= s.length() - totalLen; i++) {\n            Map<String, Integer> tempCount = new HashMap<>(wordCount);\n            int j = 0;\n            while (j < totalLen) {\n                String word = s.substring(i + j, i + j + wordLen);\n                if (tempCount.containsKey(word) && tempCount.get(word) > 0) {\n                    tempCount.put(word, tempCount.get(word) - 1);\n                    j += wordLen;\n                } else {\n                    break;\n                }\n            }\n            if (j == totalLen) {\n                result.add(i);\n            }\n        }\n        return result;\n    }\n}');
INSERT INTO `solution` VALUES (90, 30, 3, '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nint* findSubstring(char* s, char** words, int wordsSize, int* returnSize) {\n    if (!s || !words || wordsSize == 0) {\n        *returnSize = 0;\n        return NULL;\n    }\n    int wordLen = strlen(words[0]);\n    int totalLen = wordLen * wordsSize;\n    int sLen = strlen(s);\n    int* result = (int*)malloc(sLen * sizeof(int));\n    int count = 0;\n    for (int i = 0; i <= sLen - totalLen; i++) {\n        int used[wordsSize];\n        memset(used, 0, wordsSize * sizeof(int));\n        int j;\n        for (j = 0; j < totalLen; j += wordLen) {\n            int found = 0;\n            for (int k = 0; k < wordsSize; k++) {\n                if (!used[k] && strncmp(s + i + j, words[k], wordLen) == 0) {\n                    used[k] = 1;\n                    found = 1;\n                    break;\n                }\n            }\n            if (!found) break;\n        }\n        if (j == totalLen) {\n            result[count++] = i;\n        }\n    }\n    *returnSize = count;\n    return result;\n}');
INSERT INTO `solution` VALUES (91, 31, 1, 'def nextPermutation(nums):\n    i = len(nums) - 2\n    while i >= 0 and nums[i] >= nums[i+1]:\n        i -= 1\n    if i >= 0:\n        j = len(nums) - 1\n        while j > i and nums[j] <= nums[i]:\n            j -= 1\n        nums[i], nums[j] = nums[j], nums[i]\n    left, right = i + 1, len(nums) - 1\n    while left < right:\n        nums[left], nums[right] = nums[right], nums[left]\n        left += 1\n        right -= 1');
INSERT INTO `solution` VALUES (92, 31, 2, 'public class Solution {\n    public void nextPermutation(int[] nums) {\n        int i = nums.length - 2;\n        while (i >= 0 && nums[i] >= nums[i + 1]) {\n            i--;\n        }\n        if (i >= 0) {\n            int j = nums.length - 1;\n            while (j > i && nums[j] <= nums[i]) {\n                j--;\n            }\n            swap(nums, i, j);\n        }\n        reverse(nums, i + 1);\n    }\n    private void swap(int[] nums, int i, int j) {\n        int temp = nums[i];\n        nums[i] = nums[j];\n        nums[j] = temp;\n    }\n    private void reverse(int[] nums, int start) {\n        int i = start, j = nums.length - 1;\n        while (i < j) {\n            swap(nums, i, j);\n            i++;\n            j--;\n        }\n    }\n}');
INSERT INTO `solution` VALUES (93, 31, 3, '#include <stdio.h>\n\nvoid nextPermutation(int* nums, int numsSize) {\n    int i = numsSize - 2;\n    while (i >= 0 && nums[i] >= nums[i + 1]) {\n        i--;\n    }\n    if (i >= 0) {\n        int j = numsSize - 1;\n        while (j > i && nums[j] <= nums[i]) {\n            j--;\n        }\n        int temp = nums[i];\n        nums[i] = nums[j];\n        nums[j] = temp;\n    }\n    int left = i + 1, right = numsSize - 1;\n    while (left < right) {\n        int temp = nums[left];\n        nums[left] = nums[right];\n        nums[right] = temp;\n        left++;\n        right--;\n    }\n}');
INSERT INTO `solution` VALUES (97, 32, 1, 'a, b = map(int, input().split())\nprint(a + b)');
INSERT INTO `solution` VALUES (98, 32, 2, 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int a = sc.nextInt(), b = sc.nextInt();\n    System.out.println(a + b);\n  }\n}');
INSERT INTO `solution` VALUES (99, 32, 3, '#include <stdio.h>\nint main() {\n  int a, b;\n  scanf(\"%d%d\", &a, &b);\n  printf(\"%d\\n\", a + b);\n  return 0;\n}');
INSERT INTO `solution` VALUES (100, 33, 1, 'def calc_paths(m, n, mx, my):\n    board = [[0]*(n+1) for _ in range(m+1)]\n    horse_moves = [(0,0), (1,2), (2,1), (-1,2), (-2,1), (-1,-2), (-2,-1), (1,-2), (2,-1)]\n    blocked = set((mx+dx, my+dy) for dx, dy in horse_moves)\n    board[0][0] = 1\n    for i in range(m+1):\n        for j in range(n+1):\n            if (i,j) in blocked or (i == 0 and j == 0): continue\n            if i > 0: board[i][j] += board[i-1][j]\n            if j > 0: board[i][j] += board[i][j-1]\n    return board[m][n]');
INSERT INTO `solution` VALUES (101, 33, 2, 'import java.util.*;\npublic class Main {\n  static int[][] dp;\n  static boolean[][] blocked = new boolean[21][21];\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int m = sc.nextInt(), n = sc.nextInt();\n    int hx = sc.nextInt(), hy = sc.nextInt();\n    int[] dx = {0, 1, 2, -1, -2, -1, -2, 1, 2};\n    int[] dy = {0, 2, 1, 2, 1, -2, -1, -2, -1};\n    for (int i = 0; i < 9; i++) {\n      int x = hx + dx[i]; int y = hy + dy[i];\n      if (x >= 0 && y >= 0 && x <= m && y <= n) blocked[x][y] = true;\n    }\n    dp = new int[m+1][n+1];\n    dp[0][0] = blocked[0][0] ? 0 : 1;\n    for (int i = 0; i <= m; i++) {\n      for (int j = 0; j <= n; j++) {\n        if (blocked[i][j] || (i == 0 && j == 0)) continue;\n        if (i > 0) dp[i][j] += dp[i-1][j];\n        if (j > 0) dp[i][j] += dp[i][j-1];\n      }\n    }\n    System.out.println(dp[m][n]);\n  }\n}');
INSERT INTO `solution` VALUES (102, 33, 3, '#include <stdio.h>\nint dp[21][21], blocked[21][21];\nint dx[9] = {0, 1, 2, -1, -2, -1, -2, 1, 2};\nint dy[9] = {0, 2, 1, 2, 1, -2, -1, -2, -1};\nint main() {\n  int m, n, hx, hy;\n  scanf(\"%d %d %d %d\", &m, &n, &hx, &hy);\n  for (int i = 0; i < 9; i++) {\n    int x = hx + dx[i], y = hy + dy[i];\n    if (x >= 0 && x <= m && y >= 0 && y <= n) blocked[x][y] = 1;\n  }\n  dp[0][0] = blocked[0][0] ? 0 : 1;\n  for (int i = 0; i <= m; i++)\n    for (int j = 0; j <= n; j++) {\n      if (blocked[i][j] || (i == 0 && j == 0)) continue;\n      if (i > 0) dp[i][j] += dp[i-1][j];\n      if (j > 0) dp[i][j] += dp[i][j-1];\n    }\n  printf(\"%d\\n\", dp[m][n]);\n  return 0;\n}');
INSERT INTO `solution` VALUES (103, 34, 1, 'n = int(input())\\nrugs = [tuple(map(int, input().split())) for _ in range(n)]\\nx, y = map(int, input().split())\\nres = -1\\nfor i in range(n):\\n    a, b, w, h = rugs[i]\\n    if a <= x <= a + w and b <= y <= b + h:\\n        res = i + 1\\nprint(res)');
INSERT INTO `solution` VALUES (104, 34, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int[][] rugs = new int[n][4];\\n    for (int i = 0; i < n; i++)\\n      for (int j = 0; j < 4; j++) rugs[i][j] = sc.nextInt();\\n    int x = sc.nextInt(), y = sc.nextInt(), res = -1;\\n    for (int i = 0; i < n; i++) {\\n      int a = rugs[i][0], b = rugs[i][1], w = rugs[i][2], h = rugs[i][3];\\n      if (a <= x && x <= a + w && b <= y && y <= b + h)\\n        res = i + 1;\\n    }\\n    System.out.println(res);\\n  }\\n}');
INSERT INTO `solution` VALUES (105, 34, 3, '#include <stdio.h>\\nint main() {\\n  int n, x[10001], y[10001], w[10001], h[10001];\\n  scanf(\"%d\", &n);\\n  for (int i = 0; i < n; i++)\\n    scanf(\"%d%d%d%d\", &x[i], &y[i], &w[i], &h[i]);\\n  int px, py, res = -1;\\n  scanf(\"%d%d\", &px, &py);\\n  for (int i = 0; i < n; i++) {\\n    if (px >= x[i] && px <= x[i] + w[i] && py >= y[i] && py <= y[i] + h[i])\\n      res = i + 1;\\n  }\\n  printf(\"%d\\n\", res);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (106, 35, 1, 'heights = list(map(int, input().split()))\\nH = int(input())\\ncount = sum(1 for h in heights if h <= H + 30)\\nprint(count)');
INSERT INTO `solution` VALUES (107, 35, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int[] h = new int[10];\\n    for (int i = 0; i < 10; i++) h[i] = sc.nextInt();\\n    int H = sc.nextInt(), count = 0;\\n    for (int i = 0; i < 10; i++) if (h[i] <= H + 30) count++;\\n    System.out.println(count);\\n  }\\n}');
INSERT INTO `solution` VALUES (108, 35, 3, '#include <stdio.h>\\nint main() {\\n  int h[10], H, i, cnt = 0;\\n  for (i = 0; i < 10; i++) scanf(\"%d\", &h[i]);\\n  scanf(\"%d\", &H);\\n  for (i = 0; i < 10; i++) if (h[i] <= H + 30) cnt++;\\n  printf(\"%d\\n\", cnt);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (109, 36, 1, 'def solve_energy_beads(beads):\\n    n = len(beads)\\n    beads = beads * 2\\n    dp = [[0]*n*2 for _ in range(n*2)]\\n    for l in range(2, n+1):\\n        for i in range(2*n-l):\\n            j = i + l - 1\\n            for k in range(i+1, j):\\n                dp[i][j] = max(dp[i][j], dp[i][k]+dp[k][j]+beads[i]*beads[k]*beads[j])\\n    return max(dp[i][i+n-1] for i in range(n))\\n\\nn = int(input())\\nbeads = list(map(int, input().split()))\\nprint(solve_energy_beads(beads))');
INSERT INTO `solution` VALUES (110, 36, 2, 'import java.util.*;\\npublic class Main {\\n  static int[][] dp = new int[210][210];\\n  static int[] a = new int[210];\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    for (int i = 1; i <= n; i++) a[i] = sc.nextInt();\\n    for (int i = 1; i <= n; i++) a[i+n] = a[i];\\n    for (int len = 2; len <= n; len++)\\n      for (int i = 1; i + len - 1 <= 2 * n; i++) {\\n        int j = i + len - 1;\\n        for (int k = i; k < j; k++)\\n          dp[i][j] = Math.max(dp[i][j], dp[i][k] + dp[k+1][j] + a[i]*a[k+1]*a[j+1]);\\n      }\\n    int res = 0;\\n    for (int i = 1; i <= n; i++) res = Math.max(res, dp[i][i+n-1]);\\n    System.out.println(res);\\n  }\\n}');
INSERT INTO `solution` VALUES (111, 36, 3, '#include <stdio.h>\\nint max(int a, int b) { return a > b ? a : b; }\\nint main() {\\n  int n, a[210], dp[210][210] = {0}, i, j, k, len, res = 0;\\n  scanf(\"%d\", &n);\\n  for (i = 1; i <= n; i++) scanf(\"%d\", &a[i]), a[i+n] = a[i];\\n  for (len = 2; len <= n; len++)\\n    for (i = 1; i + len - 1 <= 2*n; i++) {\\n      j = i + len - 1;\\n      for (k = i; k < j; k++)\\n        dp[i][j] = max(dp[i][j], dp[i][k] + dp[k+1][j] + a[i]*a[k+1]*a[j+1]);\\n    }\\n  for (i = 1; i <= n; i++) if (res < dp[i][i+n-1]) res = dp[i][i+n-1];\\n  printf(\"%d\\n\", res);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (112, 37, 1, 'n = int(input())\\ntri = [list(map(int, input().split())) for _ in range(n)]\\nfor i in range(n-2, -1, -1):\\n    for j in range(i+1):\\n        tri[i][j] += max(tri[i+1][j], tri[i+1][j+1])\\nprint(tri[0][0])');
INSERT INTO `solution` VALUES (113, 37, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int[][] a = new int[n][n];\\n    for (int i = 0; i < n; i++)\\n      for (int j = 0; j <= i; j++)\\n        a[i][j] = sc.nextInt();\\n    for (int i = n - 2; i >= 0; i--)\\n      for (int j = 0; j <= i; j++)\\n        a[i][j] += Math.max(a[i+1][j], a[i+1][j+1]);\\n    System.out.println(a[0][0]);\\n  }\\n}');
INSERT INTO `solution` VALUES (114, 37, 3, '#include <stdio.h>\\nint max(int a, int b) { return a > b ? a : b; }\\nint main() {\\n  int n, a[100][100];\\n  scanf(\"%d\", &n);\\n  for (int i = 0; i < n; i++)\\n    for (int j = 0; j <= i; j++)\\n      scanf(\"%d\", &a[i][j]);\\n  for (int i = n - 2; i >= 0; i--)\\n    for (int j = 0; j <= i; j++)\\n      a[i][j] += max(a[i+1][j], a[i+1][j+1]);\\n  printf(\"%d\\n\", a[0][0]);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (115, 38, 1, 'n, w = map(int, input().split())\\nweights = list(map(int, input().split()))\\nweights.sort()\\ni, j, res = 0, n - 1, 0\\nwhile i <= j:\\n    if weights[i] + weights[j] <= w:\\n        i += 1\\n    j -= 1\\n    res += 1\\nprint(res)');
INSERT INTO `solution` VALUES (116, 38, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt(), w = sc.nextInt();\\n    int[] a = new int[n];\\n    for (int i = 0; i < n; i++) a[i] = sc.nextInt();\\n    Arrays.sort(a);\\n    int i = 0, j = n - 1, cnt = 0;\\n    while (i <= j) {\\n      if (a[i] + a[j] <= w) i++;\\n      j--; cnt++;\\n    }\\n    System.out.println(cnt);\\n  }\\n}');
INSERT INTO `solution` VALUES (117, 38, 3, '#include <stdio.h>\\n#include <stdlib.h>\\nint cmp(const void *a, const void *b) { return *(int *)a - *(int *)b; }\\nint main() {\\n  int n, w, i = 0, j, res = 0, a[30010];\\n  scanf(\"%d%d\", &n, &w);\\n  for (int k = 0; k < n; k++) scanf(\"%d\", &a[k]);\\n  qsort(a, n, sizeof(int), cmp);\\n  j = n - 1;\\n  while (i <= j) {\\n    if (a[i] + a[j] <= w) i++;\\n    j--; res++;\\n  }\\n  printf(\"%d\\n\", res);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (118, 39, 1, 'n = int(input())\\nfib = [0, 1, 2] + [0] * (n - 2)\\nfor i in range(3, n+1):\\n    fib[i] = fib[i-1] + fib[i-2]\\nprint(fib[n])');
INSERT INTO `solution` VALUES (119, 39, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int[] dp = new int[n+2];\\n    dp[1] = 1; dp[2] = 2;\\n    for (int i = 3; i <= n; i++)\\n      dp[i] = dp[i-1] + dp[i-2];\\n    System.out.println(dp[n]);\\n  }\\n}');
INSERT INTO `solution` VALUES (120, 39, 3, '#include <stdio.h>\\nint main() {\\n  int n, dp[100] = {0};\\n  scanf(\"%d\", &n);\\n  dp[1] = 1; dp[2] = 2;\\n  for (int i = 3; i <= n; i++)\\n    dp[i] = dp[i-1] + dp[i-2];\\n  printf(\"%d\\n\", dp[n]);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (121, 40, 1, 'a = input().strip()\\nb = input().strip()\\nresult = []\\ncarry = 0\\nfor i in range(1, max(len(a), len(b))+1):\\n    x = int(a[-i]) if i <= len(a) else 0\\n    y = int(b[-i]) if i <= len(b) else 0\\n    s = x + y + carry\\n    carry = s // 10\\n    result.append(str(s % 10))\\nif carry: result.append(str(carry))\\nprint(\"\".join(result[::-1]))');
INSERT INTO `solution` VALUES (122, 40, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    String a = sc.nextLine();\\n    String b = sc.nextLine();\\n    StringBuilder res = new StringBuilder();\\n    int carry = 0;\\n    int i = a.length()-1, j = b.length()-1;\\n    while (i >= 0 || j >= 0 || carry != 0) {\\n      int x = i >= 0 ? a.charAt(i) - \'0\' : 0;\\n      int y = j >= 0 ? b.charAt(j) - \'0\' : 0;\\n      int sum = x + y + carry;\\n      carry = sum / 10;\\n      res.append(sum % 10);\\n      i--; j--;}\\n    System.out.println(res.reverse().toString());\\n  }\\n}');
INSERT INTO `solution` VALUES (123, 40, 3, '#include <stdio.h>\\n#include <string.h>\\nint main() {\\n  char a[1010], b[1010], res[1010];\\n  int la, lb, carry = 0, i, j, k = 0;\\n  scanf(\"%s %s\", a, b);\\n  la = strlen(a); lb = strlen(b);\\n  for (i = la - 1, j = lb - 1; i >= 0 || j >= 0 || carry; i--, j--) {\\n    int x = i >= 0 ? a[i] - \'0\' : 0;\\n    int y = j >= 0 ? b[j] - \'0\' : 0;\\n    int sum = x + y + carry;\\n    res[k++] = sum % 10 + \'0\';\\n    carry = sum / 10;\\n  }\\n  for (i = k - 1; i >= 0; i--) putchar(res[i]);\\n  putchar(\'\\n\');\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (124, 41, 1, 'n = int(input())\\ntri = [list(map(int, input().split())) for _ in range(n)]\\nfor i in range(n-2, -1, -1):\\n    for j in range(i+1):\\n        tri[i][j] += max(tri[i+1][j], tri[i+1][j+1])\\nprint(tri[0][0])');
INSERT INTO `solution` VALUES (125, 41, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int[][] a = new int[n][n];\\n    for (int i = 0; i < n; i++)\\n      for (int j = 0; j <= i; j++)\\n        a[i][j] = sc.nextInt();\\n    for (int i = n - 2; i >= 0; i--)\\n      for (int j = 0; j <= i; j++)\\n        a[i][j] += Math.max(a[i+1][j], a[i+1][j+1]);\\n    System.out.println(a[0][0]);\\n  }\\n}');
INSERT INTO `solution` VALUES (126, 41, 3, '#include <stdio.h>\\nint max(int a, int b) { return a > b ? a : b; }\\nint main() {\\n  int n, a[100][100];\\n  scanf(\"%d\", &n);\\n  for (int i = 0; i < n; i++)\\n    for (int j = 0; j <= i; j++)\\n      scanf(\"%d\", &a[i][j]);\\n  for (int i = n - 2; i >= 0; i--)\\n    for (int j = 0; j <= i; j++)\\n      a[i][j] += max(a[i+1][j], a[i+1][j+1]);\\n  printf(\"%d\\n\", a[0][0]);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (127, 42, 1, 'n = int(input())\\ncnt = 0\\nfor i in range(1, int(n**0.5)+1):\\n    if n % i == 0:\\n        cnt += 1 if i * i == n else 2\\nprint(cnt)');
INSERT INTO `solution` VALUES (128, 42, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt(), cnt = 0;\\n    for (int i = 1; i * i <= n; i++) {\\n      if (n % i == 0) {\\n        cnt += (i * i == n) ? 1 : 2;\\n      }\\n    }\\n    System.out.println(cnt);\\n  }\\n}');
INSERT INTO `solution` VALUES (129, 42, 3, '#include <stdio.h>\\n#include <math.h>\\nint main() {\\n  int n, cnt = 0;\\n  scanf(\"%d\", &n);\\n  for (int i = 1; i <= (int)sqrt(n); i++) {\\n    if (n % i == 0) {\\n      cnt += (i * i == n) ? 1 : 2;\\n    }\\n  }\\n  printf(\"%d\\n\", cnt);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (130, 43, 1, 'n = int(input())\\na = list(map(int, input().split()))\\nmax_sum = cur_sum = a[0]\\nfor x in a[1:]:\\n    cur_sum = max(x, cur_sum + x)\\n    max_sum = max(max_sum, cur_sum)\\nprint(max_sum)');
INSERT INTO `solution` VALUES (131, 43, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int[] a = new int[n];\\n    for (int i = 0; i < n; i++) a[i] = sc.nextInt();\\n    int maxSum = a[0], curSum = a[0];\\n    for (int i = 1; i < n; i++) {\\n      curSum = Math.max(a[i], curSum + a[i]);\\n      maxSum = Math.max(maxSum, curSum);\\n    }\\n    System.out.println(maxSum);\\n  }\\n}');
INSERT INTO `solution` VALUES (132, 43, 3, '#include <stdio.h>\\nint main() {\\n  int n; scanf(\"%d\", &n);\\n  int a[100010], i;\\n  for (i = 0; i < n; i++) scanf(\"%d\", &a[i]);\\n  int maxSum = a[0], curSum = a[0];\\n  for (i = 1; i < n; i++) {\\n    if (curSum < 0) curSum = a[i];\\n    else curSum += a[i];\\n    if (curSum > maxSum) maxSum = curSum;\\n  }\\n  printf(\"%d\\n\", maxSum);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (133, 44, 1, 'n = int(input())\\na = list(map(int, input().split()))\\nprint(sum(a))');
INSERT INTO `solution` VALUES (134, 44, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int sum = 0;\\n    for (int i = 0; i < n; i++) sum += sc.nextInt();\\n    System.out.println(sum);\\n  }\\n}');
INSERT INTO `solution` VALUES (135, 44, 3, '#include <stdio.h>\\nint main() {\\n  int n, sum = 0, x;\\n  scanf(\"%d\", &n);\\n  for (int i = 0; i < n; i++) {\\n    scanf(\"%d\", &x);\\n    sum += x;\\n  }\\n  printf(\"%d\\n\", sum);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (136, 45, 1, 'n = int(input())\\ndef is_prime(x):\\n    if x < 2: return False\\n    for i in range(2, int(x**0.5) + 1):\\n        if x % i == 0:\\n            return False\\n    return True\\nprint(\"YES\" if is_prime(n) else \"NO\")');
INSERT INTO `solution` VALUES (137, 45, 2, 'import java.util.*;\\npublic class Main {\\n  public static boolean isPrime(int n) {\\n    if (n < 2) return false;\\n    for (int i = 2; i * i <= n; i++)\\n      if (n % i == 0) return false;\\n    return true;\\n  }\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    System.out.println(isPrime(n) ? \"YES\" : \"NO\");\\n  }\\n}');
INSERT INTO `solution` VALUES (138, 45, 3, '#include <stdio.h>\\n#include <math.h>\\nint isPrime(int n) {\\n  if (n < 2) return 0;\\n  for (int i = 2; i <= (int)sqrt(n); i++) {\\n    if (n % i == 0) return 0;\\n  }\\n  return 1;\\n}\\nint main() {\\n  int n; scanf(\"%d\", &n);\\n  printf(\"%s\\n\", isPrime(n) ? \"YES\" : \"NO\");\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (139, 46, 1, 'def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\na, b = map(int, input().split())\\nprint(gcd(a, b))');
INSERT INTO `solution` VALUES (140, 46, 2, 'import java.util.*;\\npublic class Main {\\n  public static int gcd(int a, int b) {\\n    while (b != 0) {\\n      int t = b; b = a % b; a = t;\\n    }\\n    return a;\\n  }\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int a = sc.nextInt(), b = sc.nextInt();\\n    System.out.println(gcd(a, b));\\n  }\\n}');
INSERT INTO `solution` VALUES (141, 46, 3, '#include <stdio.h>\\nint gcd(int a, int b) {\\n  while (b) {\\n    int t = b;\\n    b = a % b;\\n    a = t;\\n  }\\n  return a;\\n}\\nint main() {\\n  int a, b; scanf(\"%d %d\", &a, &b);\\n  printf(\"%d\\n\", gcd(a, b));\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (142, 47, 1, 'def factorial(n):\\n    res = 1\\n    for i in range(2, n+1):\\n        res *= i\\n    return res\\nn = int(input())\\nprint(factorial(n))');
INSERT INTO `solution` VALUES (143, 47, 2, 'import java.util.*;\\npublic class Main {\\n  public static long factorial(int n) {\\n    long res = 1;\\n    for (int i = 2; i <= n; i++) res *= i;\\n    return res;\\n  }\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    System.out.println(factorial(n));\\n  }\\n}');
INSERT INTO `solution` VALUES (144, 47, 3, '#include <stdio.h>\\nlong factorial(int n) {\\n  long res = 1;\\n  for (int i = 2; i <= n; i++) res *= i;\\n  return res;\\n}\\nint main() {\\n  int n; scanf(\"%d\", &n);\\n  printf(\"%ld\\n\", factorial(n));\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (145, 48, 1, 'n = int(input())\\na, b = 0, 1\\nfor _ in range(n):\\n    a, b = b, a + b\\nprint(a)');
INSERT INTO `solution` VALUES (146, 48, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int a = 0, b = 1;\\n    for (int i = 0; i < n; i++) {\\n      int temp = a;\\n      a = b;\\n      b = temp + b;\\n    }\\n    System.out.println(a);\\n  }\\n}');
INSERT INTO `solution` VALUES (147, 48, 3, '#include <stdio.h>\\nint main() {\\n  int n; scanf(\"%d\", &n);\\n  int a = 0, b = 1;\\n  for (int i = 0; i < n; i++) {\\n    int temp = a;\\n    a = b;\\n    b = temp + b;\\n  }\\n  printf(\"%d\\n\", a);\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (148, 49, 1, 'n = int(input())\\ns = str(n)\\nsum_cube = sum(int(x)**3 for x in s)\\nprint(\"YES\" if sum_cube == n else \"NO\")');
INSERT INTO `solution` VALUES (149, 49, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    int n = sc.nextInt();\\n    int sum = 0, temp = n;\\n    while (temp > 0) {\\n      int d = temp % 10;\\n      sum += d * d * d;\\n      temp /= 10;\\n    }\\n    System.out.println(sum == n ? \"YES\" : \"NO\");\\n  }\\n}');
INSERT INTO `solution` VALUES (150, 49, 3, '#include <stdio.h>\\nint main() {\\n  int n, sum = 0, temp;\\n  scanf(\"%d\", &n);\\n  temp = n;\\n  while (temp) {\\n    int d = temp % 10;\\n    sum += d * d * d;\\n    temp /= 10;\\n  }\\n  printf(\"%s\\n\", sum == n ? \"YES\" : \"NO\");\\n  return 0;\\n}');
INSERT INTO `solution` VALUES (151, 50, 1, 'from collections import Counter\\ns = input().strip()\\ncnt = Counter(s)\\nfor ch in sorted(cnt):\\n    print(f\"{ch}:{cnt[ch]}\")');
INSERT INTO `solution` VALUES (152, 50, 2, 'import java.util.*;\\npublic class Main {\\n  public static void main(String[] args) {\\n    Scanner sc = new Scanner(System.in);\\n    String s = sc.nextLine();\\n    Map<Character, Integer> map = new TreeMap<>();\\n    for (char c : s.toCharArray()) {\\n      map.put(c, map.getOrDefault(c, 0) + 1);\\n    }\\n    for (Map.Entry<Character, Integer> e : map.entrySet()) {\\n      System.out.println(e.getKey() + \":\" + e.getValue());\\n    }\\n  }\\n}');
INSERT INTO `solution` VALUES (153, 50, 3, '#include <stdio.h>\\n#include <string.h>\\nint main() {\\n  char s[1010];\\n  int cnt[256] = {0};\\n  scanf(\"%s\", s);\\n  for (int i = 0; s[i]; i++) cnt[(int)s[i]]++;\\n  for (int i = 0; i < 256; i++) {\\n    if (cnt[i]) printf(\"%c:%d\\n\", i, cnt[i]);\\n  }\\n  return 0;\\n}');

SET FOREIGN_KEY_CHECKS = 1;
